server:
  port: 24000
  tomcat:
    uri-encoding: UTF-8

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss


logging:
  level:
    org.springframework: debug
    com.auth.service.web.dao: debug
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000

#ribbon的超时时间
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

# spring security 配置
security:
  oauth2:
    resource:
      loadBalanced: true
      token-info-uri: http://localhost:24000/oauth/check_token
    # 通用放行URL，服务个性化，请在对应配置文件覆盖
    ignore:
      urls:
        - /v2/api-docs
        - /actuator/**